package pl.anarchia.itemy;
import org.bukkit.*;import org.bukkit.attribute.Attribute;import org.bukkit.block.Block;import org.bukkit.command.*;import org.bukkit.enchantments.Enchantment;import org.bukkit.entity.*;import org.bukkit.event.*;import org.bukkit.event.block.Action;import org.bukkit.event.entity.*;import org.bukkit.event.player.*;import org.bukkit.inventory.*;import org.bukkit.inventory.meta.ItemMeta;import org.bukkit.persistence.PersistentDataType;import org.bukkit.potion.*;import org.bukkit.plugin.java.JavaPlugin;import java.util.*;
public class AnarchiaItemy extends JavaPlugin implements Listener,CommandExecutor{
 NamespacedKey key; static final Map<String,String>N=new LinkedHashMap<>();
 static{String[][]x={{"anarchicznyluk","Anarchiczny Łuk"},{"anarchicznymiecz","Anarchiczny miecz"},{"anarchicznykilof","Anarchiczny kilof"},{"anarchicznytrojzab","Anarchiczny Trójząb"},{"cieplemleko","Ciepłe mleko"},{"krewwampira","Krew wampira"},{"magicznycukierek","Magiczny cukierek"},{"piernik","Piernik"},{"boskitopor","Boski topór"},{"parawan","Parawan"},{"dynamit","Dynamit"},{"zmutowanycreeper","Jajko zmutowanego creepera"},{"plecakdrakuli","Plecak Drakuli"},{"kosa","Kosa"},{"zatrutyolowek","Zatruty ołówek"},{"zlamaneserce","Złamane serce"},{"zajeczymiecz","Zajęczy miecz"},{"lewejajko","Lewe jajko"},{"marchewkowymiecz","Marchewkowy miecz"},{"kostkarubika","Kostka rubika"},{"siekieragrincha","Siekiera Grincha"},{"mace","Mace"},{"totemulaskawienia","Totem ułaskawienia"}};for(String[]a:x)N.put(a[0],a[1]);}
 public void onEnable(){key=new NamespacedKey(this,"item");getCommand("anarchiaitemy").setExecutor(this);getServer().getPluginManager().registerEvents(this,this);}
 ItemStack item(String id){Material m=id.contains("luk")?Material.BOW:id.contains("kilof")?Material.NETHERITE_PICKAXE:id.contains("trojzab")?Material.TRIDENT:id.contains("jajko")?Material.CREEPER_SPAWN_EGG:id.contains("mleko")?Material.MILK_BUCKET:Material.NETHERITE_SWORD;ItemStack i=new ItemStack(m);ItemMeta q=i.getItemMeta();q.setDisplayName(ChatColor.GOLD+N.getOrDefault(id,id));q.getPersistentDataContainer().set(key,PersistentDataType.STRING,id);i.setItemMeta(q);return i;}
 String id(ItemStack i){return i!=null&&i.hasItemMeta()?i.getItemMeta().getPersistentDataContainer().get(key,PersistentDataType.STRING):null;}

 @EventHandler public void interact(PlayerInteractEvent e){if(e.getAction()==Action.PHYSICAL)return; Player p=e.getPlayer();String id=id(e.getItem());if(id==null)return;
  if(id.equals("cieplemleko")){e.setCancelled(true);for(PotionEffect x:new ArrayList<>(p.getActivePotionEffects()))if(x.getType().equals(PotionEffectType.POISON)||x.getType().equals(PotionEffectType.WITHER)||x.getType().equals(PotionEffectType.SLOWNESS)||x.getType().equals(PotionEffectType.WEAKNESS)||x.getType().equals(PotionEffectType.BLINDNESS))p.removePotionEffect(x.getType());}
  else if(id.equals("krewwampira")){e.setCancelled(true);p.setHealth(p.getAttribute(Attribute.MAX_HEALTH).getValue());}
  else if(id.equals("magicznycukierek")){e.setCancelled(true);p.addPotionEffect(new PotionEffect(PotionEffectType.SPEED,100,4));}
  else if(id.equals("piernik")){e.setCancelled(true);p.addPotionEffect(new PotionEffect(PotionEffectType.HASTE,200,9));}
  else if(id.equals("boskitopor")||id.equals("parawan")){e.setCancelled(true);p.addPotionEffect(new PotionEffect(PotionEffectType.RESISTANCE,60,4));for(Entity z:p.getNearbyEntities(6,4,6))if(z instanceof Player q&&q!=p)q.setVelocity(q.getLocation().toVector().subtract(p.getLocation().toVector()).normalize().multiply(1.5).setY(.7));}
  else if(id.equals("dynamit")){e.setCancelled(true);Block b=p.getTargetBlockExact(6);if(b!=null&&b.getType()==Material.BEDROCK)b.setType(Material.AIR);}
  else if(id.equals("zmutowanycreeper")){e.setCancelled(true);Creeper c=(Creeper)p.getWorld().spawnEntity(p.getLocation().add(p.getLocation().getDirection().multiply(2)),EntityType.CREEPER);c.setPowered(true);c.setExplosionRadius(5);}
  else if(id.equals("plecakdrakuli")){e.setCancelled(true);p.openInventory(Bukkit.createInventory(null,27,ChatColor.DARK_RED+"Plecak Drakuli"));}
 }
 @EventHandler public void hit(EntityDamageByEntityEvent e){if(!(e.getDamager() instanceof Player p)||!(e.getEntity() instanceof Player q))return;String id=id(p.getInventory().getItemInMainHand());if(id==null)return;
  switch(id){case "kosa"->q.addPotionEffect(new PotionEffect(PotionEffectType.BLINDNESS,100,1));case "zatrutyolowek"->q.addPotionEffect(new PotionEffect(PotionEffectType.POISON,100,1));case "zlamaneserce"-> {q.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS,100,1));q.addPotionEffect(new PotionEffect(PotionEffectType.SLOW_FALLING,100,0));}case "zajeczymiecz"->q.addPotionEffect(new PotionEffect(PotionEffectType.JUMP_BOOST,80,128));case "lewejajko"->q.setVelocity(q.getVelocity().setY(1.4));case "marchewkowymiecz"->q.addPotionEffect(new PotionEffect(PotionEffectType.SLOWNESS,20,10));case "kostkarubika"-> {List<ItemStack> a=new ArrayList<>(Arrays.asList(q.getInventory().getContents()));Collections.shuffle(a);q.getInventory().setContents(a.toArray(new ItemStack[0]));}case "siekieragrincha"-> {q.getWorld().strikeLightning(q.getLocation());e.setDamage(q.getHealth()*.3);}case "mace"-> {if(q.getWorld().getEnvironment()!=World.Environment.THE_END)e.setDamage(.1);} }
 }
 @EventHandler public void death(PlayerDeathEvent e){Player dead=e.getEntity();if(dead.getInventory().containsAtLeast(item("totemulaskawienia"),1)){e.setKeepInventory(true);e.getDrops().clear();}}
 @EventHandler public void join(PlayerJoinEvent e){ }
 public boolean onCommand(CommandSender s,Command c,String l,String[] a){if(!s.hasPermission("anarchiaitemy.admin")){s.sendMessage(ChatColor.RED+"Brak uprawnień.");return true;}if(a.length==0){s.sendMessage(ChatColor.YELLOW+"/anarchiaitemy giveItem <id> [gracz] | menuPreview | enchant");return true;}if(a[0].equalsIgnoreCase("giveItem")&&a.length>=2){Player p=a.length>=3?Bukkit.getPlayer(a[2]):(s instanceof Player?(Player)s:null);if(p==null){s.sendMessage("Nie znaleziono gracza");return true;}p.getInventory().addItem(item(a[1].toLowerCase()));s.sendMessage(ChatColor.GREEN+"Otrzymano przedmiot.");}else if(a[0].equalsIgnoreCase("menuPreview")){if(s instanceof Player p){Inventory inv=Bukkit.createInventory(null,54,ChatColor.DARK_AQUA+"Podgląd eventówek");for(String id:N.keySet())inv.addItem(item(id));p.openInventory(inv);}}else if(a[0].equalsIgnoreCase("reload")){reloadConfig();s.sendMessage("Przeładowano.");}return true;}
}
